pvnn:
  lr: 0.005
  epochs: 2000
  batch_size: 128
  dataset: cora
  dropout: 0.2
  weight_decay: 0.001
  hidden_dim: 16
  curvature: 0.5
  num_runs: 5
  print_interval: 100
  use_bias: true
  patience: 200
  inner_act: none
  outer_act: tangent
