pvnn:
  lr: 0.005
  epochs: 2000
  batch_size: 128
  dataset: cora
  dropout: 0.2
  weight_decay: 0.001
  hidden_dim: 16
  curvature: 0.5
  num_runs: 5
  print_interval: 100
  use_bias: true
  patience: 200
  inner_act: none
  outer_act: direct_tanh
  no_proj_exp: false
  use_mid_bn: false
  use_mid_log_euc_bn: false
  gyrobn:
    use_euclid_stats: false
    use_gyro_midpoint: true
    clamp_factor: 3.0
    var_floor: 0.1
    max_tan_norm: 20.0
    scalar_sinh_clip: 20.0
    use_post_gain: false
